# Generated by Django 4.1.7 on 2023-07-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Student_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_in', models.DateTimeField(auto_now=True)),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sign_in.bathroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sign_in.student')),
            ],
        ),
    ]
