# Generated by Django 4.2.3 on 2023-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0005_rename_student_id_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
