# Generated by Django 4.1.7 on 2023-07-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sign_in', '0002_logs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='Time_out',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='bathroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sign_in.bathroom'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_in.student'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
