# Generated by Django 4.2.3 on 2023-07-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0004_alter_logs_time_out_alter_logs_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='student_id',
        ),
    ]
