# Generated by Django 4.2.3 on 2023-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0008_alter_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='color',
            field=models.CharField(max_length=7, default='#FF0000'),
        ),
    ]
