# Generated by Django 4.2.3 on 2023-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0009_auto_20230801_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='max_people_allowed',
            field=models.IntegerField(default = 2)
        ),
    ]
