# Generated by Django 4.2.3 on 2023-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0010_auto_20230802_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='max_people_allowed',
            field=models.PositiveIntegerField(default = 2)
        ),
    ]
