# Generated by Django 4.2.3 on 2023-08-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sign_in', '0011_auto_20230802_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sign_in.bathroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
